export interface Student { 
  id: string;
  name: string; // 姓名
  gender: string; // 性別
  grade: '1' | '2' | '3' | '4' | '5' | '6'; // 年級
  class: string; // 班級 (1-6)
  family_background: string; // 家庭背景
  is_disadvantaged: '是' | '否'; // 是否弱勢生
  cultural_disadvantage_factors: string; // 文化不利因素
  personal_background_notes: string; // 個人背景補充
  registration_motivation: string; // 報名動機
  student_type: '新生' | '舊生'; // 新舊生：新生/舊生
  account_username: string; // 後台帳號
  account_password: string; // 後台密碼
  email: string; // 常用電子信箱
  created_at: string;
  updated_at: string;
};

export interface User {
  id: string;
  email: string;
  name: string;
  role: string;
  created_at: string;
  updated_at: string;
};

export type StudentFilePreview = Omit<Omit<Omit<Student, 'id'>, 'created_at'>, 'updated_at'>;

// 模擬學生數據
export const mockStudents: Student[] = [
  {
    id: "1",
    name: "王小明",
    gender: "男",
    grade: "2",
    class: '1',
    family_background: "雙親家庭，父母皆為上班族",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "對程式設計有濃厚興趣",
    registration_motivation: "希望能透過課程提升自己的專業能力",
    student_type: "新生",
    account_username: "wangxm",
    account_password: "pass1234",
    email: "student1@example.com",
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "李小華",
    gender: "女",
    grade: "1",
    class: '2',
    family_background: "單親家庭，與母親同住",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "經濟弱勢",
    personal_background_notes: "積極向上，課餘時間打工貼補家用",
    registration_motivation: "希望能增加就業競爭力",
    student_type: "新生",
    account_username: "lixh",
    account_password: "pass5678",
    email: "student2@example.com",
    created_at: "2023-01-02T00:00:00Z",
    updated_at: "2023-01-02T00:00:00Z",
  },
  {
    id: "3",
    name: "張小芳",
    gender: "女",
    grade: "3",
    class: '3',
    family_background: "雙親家庭，家中經營小型企業",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "擅長人際溝通，有領導能力",
    registration_motivation: "想學習更多商業與技術結合的知識",
    student_type: "舊生",
    account_username: "zhangxf",
    account_password: "zhang123",
    email: "student3@example.com",
    created_at: "2023-01-03T00:00:00Z",
    updated_at: "2023-01-03T00:00:00Z",
  },
  {
    id: "4",
    name: "陳小強",
    gender: "男",
    grade: "4",
    class: '4',
    family_background: "雙親家庭，父親為工程師",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "已有多個專案開發經驗",
    registration_motivation: "為畢業後就業做準備",
    student_type: "舊生",
    account_username: "chenxq",
    account_password: "chen456",
    email: "student4@example.com",
    created_at: "2023-01-04T00:00:00Z",
    updated_at: "2023-01-04T00:00:00Z",
  },
  {
    id: "5",
    name: "林小美",
    gender: "女",
    grade: "2",
    class: '5',
    family_background: "雙親家庭，家住偏遠地區",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "居住偏遠地區",
    personal_background_notes: "喜歡數學與物理",
    registration_motivation: "想增強電腦專業技能",
    student_type: "舊生",
    account_username: "linxm",
    account_password: "lin789",
    email: "student5@example.com",
    created_at: "2023-01-05T00:00:00Z",
    updated_at: "2023-01-05T00:00:00Z",
  },
  {
    id: "6",
    name: "黃小剛",
    gender: "男",
    grade: "1",
    class: '6',
    family_background: "雙親家庭，父母皆為教師",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "對商業分析有興趣",
    registration_motivation: "希望能學習數據分析技能",
    student_type: "新生",
    account_username: "huangxg",
    account_password: "huang123",
    email: "student6@example.com",
    created_at: "2023-01-06T00:00:00Z",
    updated_at: "2023-01-06T00:00:00Z",
  },
  {
    id: "7",
    name: "劉小芬",
    gender: "女",
    grade: "3",
    class: '1',
    family_background: "單親家庭，與父親同住",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "熱愛程式開發",
    registration_motivation: "想深入學習軟體工程實踐",
    student_type: "舊生",
    account_username: "liuxf",
    account_password: "liu456",
    email: "student7@example.com",
    created_at: "2023-01-07T00:00:00Z",
    updated_at: "2023-01-07T00:00:00Z",
  },
  {
    id: "8",
    name: "吳小傑",
    gender: "男",
    grade: "4",
    class: '2',
    family_background: "隔代教養，與祖父母同住",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "隔代教養",
    personal_background_notes: "自學能力強",
    registration_motivation: "為研究所考試做準備",
    student_type: "舊生",
    account_username: "wuxj",
    account_password: "wu789",
    email: "student8@example.com",
    created_at: "2023-01-08T00:00:00Z",
    updated_at: "2023-01-08T00:00:00Z",
  },
  {
    id: "9",
    name: "楊小雯",
    gender: "女",
    grade: "2",
    class: '3',
    family_background: "雙親家庭，家中有三個小孩",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "經濟弱勢",
    personal_background_notes: "擅長組織活動",
    registration_motivation: "想學習專案管理知識",
    student_type: "舊生",
    account_username: "yangxw",
    account_password: "yang123",
    email: "student9@example.com",
    created_at: "2023-01-09T00:00:00Z",
    updated_at: "2023-01-09T00:00:00Z",
  },
  {
    id: "10",
    name: "趙小龍",
    gender: "男",
    grade: "1",
    class: '4',
    family_background: "雙親家庭，父母為小商家老闆",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "對人工智能特別感興趣",
    registration_motivation: "希望能參與研究項目",
    student_type: "新生",
    account_username: "zhaoxl",
    account_password: "zhao456",
    email: "student10@example.com",
    created_at: "2023-01-10T00:00:00Z",
    updated_at: "2023-01-10T00:00:00Z",
  },
  {
    id: "11",
    name: "孫小梅",
    gender: "女",
    grade: "3",
    class: '5',
    family_background: "雙親家庭，家住原住民部落",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "原住民身份",
    personal_background_notes: "熱愛文化傳承",
    registration_motivation: "希望將科技帶回部落幫助社區",
    student_type: "舊生",
    account_username: "sunxm",
    account_password: "sun789",
    email: "student11@example.com",
    created_at: "2023-01-11T00:00:00Z",
    updated_at: "2023-01-11T00:00:00Z",
  },
  {
    id: "12",
    name: "周小倫",
    gender: "男",
    grade: "4",
    class: '6',
    family_background: "單親家庭，母親為公務員",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "曾獲多次程式競賽獎項",
    registration_motivation: "為就業做最後準備",
    student_type: "舊生",
    account_username: "zhouxl",
    account_password: "zhou123",
    email: "student12@example.com",
    created_at: "2023-01-12T00:00:00Z",
    updated_at: "2023-01-12T00:00:00Z",
  },
  {
    id: "13",
    name: "胡小玲",
    gender: "女",
    grade: "2",
    class: '1',
    family_background: "雙親家庭，家中有四個小孩",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "經濟弱勢",
    personal_background_notes: "課餘時間在圖書館打工",
    registration_motivation: "希望能學習新技術提升自我",
    student_type: "舊生",
    account_username: "huxl",
    account_password: "hu456",
    email: "student13@example.com",
    created_at: "2023-01-13T00:00:00Z",
    updated_at: "2023-01-13T00:00:00Z",
  },
  {
    id: "14",
    name: "郭小雄",
    gender: "男",
    grade: "1",
    class: '2',
    family_background: "雙親家庭，父母為醫生",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "擅長理論研究",
    registration_motivation: "希望探索電機與計算機交叉領域",
    student_type: "新生",
    account_username: "guoxx",
    account_password: "guo789",
    email: "student14@example.com",
    created_at: "2023-01-14T00:00:00Z",
    updated_at: "2023-01-14T00:00:00Z",
  },
  {
    id: "15",
    name: "鄭小婷",
    gender: "女",
    grade: "3",
    class: '3',
    family_background: "雙親家庭，家中經營農場",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "農村地區",
    personal_background_notes: "對數據科學有強烈興趣",
    registration_motivation: "希望能將數據分析應用於農業",
    student_type: "舊生",
    account_username: "zhengxt",
    account_password: "zheng123",
    email: "student15@example.com",
    created_at: "2023-01-15T00:00:00Z",
    updated_at: "2023-01-15T00:00:00Z",
  },
  {
    id: "16",
    name: "何小偉",
    gender: "男",
    grade: "4",
    class: '4',
    family_background: "雙親家庭，父親為工程師",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "已有兩份實習經驗",
    registration_motivation: "希望能強化履歷",
    student_type: "舊生",
    account_username: "hexw",
    account_password: "he456",
    email: "student16@example.com",
    created_at: "2023-01-16T00:00:00Z",
    updated_at: "2023-01-16T00:00:00Z",
  },
  {
    id: "17",
    name: "馬小琳",
    gender: "女",
    grade: "2",
    class: '5',
    family_background: "新住民家庭，母親來自越南",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "新住民家庭",
    personal_background_notes: "語言能力強，會三種語言",
    registration_motivation: "希望能提升專業技能",
    student_type: "舊生",
    account_username: "maxl",
    account_password: "ma789",
    email: "student17@example.com",
    created_at: "2023-01-17T00:00:00Z",
    updated_at: "2023-01-17T00:00:00Z",
  },
  {
    id: "18",
    name: "蕭小宏",
    gender: "男",
    grade: "1",
    class: '6',
    family_background: "雙親家庭，父親為教授",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "對商業分析有強烈興趣",
    registration_motivation: "希望能提早接觸專業知識",
    student_type: "新生",
    account_username: "xiaoxh",
    account_password: "xiao123",
    email: "student18@example.com",
    created_at: "2023-01-18T00:00:00Z",
    updated_at: "2023-01-18T00:00:00Z",
  },
  {
    id: "19",
    name: "朱小瑜",
    gender: "女",
    grade: "3",
    class: '1',
    family_background: "雙親家庭，家中經營小餐館",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "參與過多個開源項目",
    registration_motivation: "希望能深入理解軟體開發流程",
    student_type: "舊生",
    account_username: "zhuxy",
    account_password: "zhu456",
    email: "student19@example.com",
    created_at: "2023-01-19T00:00:00Z",
    updated_at: "2023-01-19T00:00:00Z",
  },
  {
    id: "20",
    name: "唐小鈞",
    gender: "男",
    grade: "4",
    class: '2',
    family_background: "單親家庭，父親早逝",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "經濟弱勢",
    personal_background_notes: "堅強自立，課餘做家教",
    registration_motivation: "希望能增強就業競爭力",
    student_type: "舊生",
    account_username: "tangxj",
    account_password: "tang789",
    email: "student20@example.com",
    created_at: "2023-01-20T00:00:00Z",
    updated_at: "2023-01-20T00:00:00Z",
  },
  {
    id: "21",
    name: "宋小萱",
    gender: "女",
    grade: "2",
    class: '3',
    family_background: "隔代教養，與祖母同住",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "隔代教養",
    personal_background_notes: "性格獨立，自主學習能力強",
    registration_motivation: "希望能提升專業能力",
    student_type: "舊生",
    account_username: "songxx",
    account_password: "song123",
    email: "student21@example.com",
    created_at: "2023-01-21T00:00:00Z",
    updated_at: "2023-01-21T00:00:00Z",
  },
  {
    id: "22",
    name: "高小峰",
    gender: "男",
    grade: "1",
    class: '4',
    family_background: "雙親家庭，父母為企業主管",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "從高中開始自學程式設計",
    registration_motivation: "希望能系統性學習計算機科學",
    student_type: "新生",
    account_username: "gaoxf",
    account_password: "gao456",
    email: "student22@example.com",
    created_at: "2023-01-22T00:00:00Z",
    updated_at: "2023-01-22T00:00:00Z",
  },
  {
    id: "23",
    name: "盧小琪",
    gender: "女",
    grade: "3",
    class: '5',
    family_background: "雙親家庭，家住離島",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "離島地區",
    personal_background_notes: "對電路設計特別有興趣",
    registration_motivation: "希望能拓展知識面",
    student_type: "舊生",
    account_username: "luxq",
    account_password: "lu789",
    email: "student23@example.com",
    created_at: "2023-01-23T00:00:00Z",
    updated_at: "2023-01-23T00:00:00Z",
  },
  {
    id: "24",
    name: "曾小豪",
    gender: "男",
    grade: "4",
    class: '6',
    family_background: "雙親家庭，父母皆為教師",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "曾獲創業比賽獎項",
    registration_motivation: "希望能將所學應用於創業",
    student_type: "舊生",
    account_username: "zengxh",
    account_password: "zeng123",
    email: "student24@example.com",
    created_at: "2023-01-24T00:00:00Z",
    updated_at: "2023-01-24T00:00:00Z",
  },
  {
    id: "25",
    name: "方小儀",
    gender: "女",
    grade: "2",
    class: '1',
    family_background: "單親家庭，與母親同住",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "經濟弱勢",
    personal_background_notes: "喜歡解決問題，善於邏輯思考",
    registration_motivation: "希望能學習更多前沿技術",
    student_type: "舊生",
    account_username: "fangxy",
    account_password: "fang456",
    email: "student25@example.com",
    created_at: "2023-01-25T00:00:00Z",
    updated_at: "2023-01-25T00:00:00Z",
  },
]

// 模擬用戶數據
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@example.com",
    name: "管理員",
    role: "admin",
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "2",
    email: "teacher1@example.com",
    name: "王老師",
    role: "teacher",
    created_at: "2023-01-02T00:00:00Z",
    updated_at: "2023-01-02T00:00:00Z",
  },
  {
    id: "3",
    email: "teacher2@example.com",
    name: "李老師",
    role: "teacher",
    created_at: "2023-01-03T00:00:00Z",
    updated_at: "2023-01-03T00:00:00Z",
  },
  {
    id: "4",
    email: "teacher3@example.com",
    name: "張老師",
    role: "teacher",
    created_at: "2023-01-04T00:00:00Z",
    updated_at: "2023-01-04T00:00:00Z",
  },
  {
    id: "5",
    email: "teacher4@example.com",
    name: "陳老師",
    role: "teacher",
    created_at: "2023-01-05T00:00:00Z",
    updated_at: "2023-01-05T00:00:00Z",
  },
  {
    id: "6",
    email: "teacher5@example.com",
    name: "林老師",
    role: "teacher",
    created_at: "2023-01-06T00:00:00Z",
    updated_at: "2023-01-06T00:00:00Z",
  },
]

// 模擬檔案上傳預覽數據
export const mockFilePreviewData: StudentFilePreview[] = [
  {
    name: "陳大明",
    gender: "男",
    grade: "1",
    class: '1',
    family_background: "雙親家庭，父親為工程師",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "對機器學習有濃厚興趣",
    registration_motivation: "希望能接觸更多專業知識",
    student_type: "新生",
    account_username: "chendm",
    account_password: "chen123",
    email: "chen@example.com",
  },
  {
    name: "林小華",
    gender: "女",
    grade: "2",
    class: '2',
    family_background: "單親家庭，母親為護士",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "經濟弱勢",
    personal_background_notes: "喜愛電子設計",
    registration_motivation: "希望能增加專業技能",
    student_type: "舊生",
    account_username: "linxh",
    account_password: "lin456",
    email: "lin@example.com",
  },
  {
    name: "張小芳",
    gender: "女",
    grade: "3",
    class: '3',
    family_background: "雙親家庭，父母經營小店",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "熱愛數據分析",
    registration_motivation: "希望能應用所學於實務",
    student_type: "舊生",
    account_username: "zhangxf",
    account_password: "zhang789",
    email: "chang@example.com",
  },
  {
    name: "李小強",
    gender: "男",
    grade: "4",
    class: '4',
    family_background: "隔代教養，由祖父母撫養",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "隔代教養",
    personal_background_notes: "程式能力出色",
    registration_motivation: "為就業做準備",
    student_type: "舊生",
    account_username: "leexq",
    account_password: "lee123",
    email: "lee@example.com",
  },
  {
    name: "王小美",
    gender: "女",
    grade: "2",
    class: '5',
    family_background: "新住民家庭，父親為台灣人，母親為泰國人",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "新住民",
    personal_background_notes: "語言能力強",
    registration_motivation: "希望增強專業知識",
    student_type: "舊生",
    account_username: "wangxm",
    account_password: "wang456",
    email: "wang@example.com",
  },
  {
    name: "黃小剛",
    gender: "男",
    grade: "1",
    class: '6',
    family_background: "雙親家庭，父母皆為公務員",
    is_disadvantaged: '否',
    cultural_disadvantage_factors: "無",
    personal_background_notes: "善於邏輯思考",
    registration_motivation: "希望未來能進入科技業",
    student_type: "新生",
    account_username: "huangxg",
    account_password: "huang789",
    email: "huang@example.com",
  },
  {
    name: "劉小芬",
    gender: "女",
    grade: "3",
    class: '1',
    family_background: "雙親家庭，家中經營農場",
    is_disadvantaged: '是',
    cultural_disadvantage_factors: "農村地區",
    personal_background_notes: "對資訊應用於傳統產業有興趣",
    registration_motivation: "希望學習新技術應用於家庭事業",
    student_type: "舊生",
    account_username: "liuxf",
    account_password: "liu123",
    email: "liu@example.com",
  },
]

// 隨機生成教師-學生關聯數據
function generateRandomTeacherStudentAccess() {
  const access = []
  const teacherIds = mockUsers.filter((user) => user.role === "teacher").map((teacher) => teacher.id)

  // 為每個學生隨機分配1-3位教師
  for (const student of mockStudents) {
    // 隨機決定分配給這個學生的教師數量 (1-3)
    const teacherCount = Math.floor(Math.random() * 3) + 1

    // 隨機選擇不重複的教師
    const shuffledTeachers = [...teacherIds].sort(() => 0.5 - Math.random())
    const selectedTeachers = shuffledTeachers.slice(0, teacherCount)

    // 創建關聯記錄
    for (const teacherId of selectedTeachers) {
      access.push({
        id: `${access.length + 1}`,
        teacher_id: teacherId,
        student_id: student.id,
        created_at: "2023-01-01T00:00:00Z",
      })
    }
  }

  return access
}

// 模擬教師-學生關聯數據
export const mockTeacherStudentAccess = generateRandomTeacherStudentAccess()

// 模擬當前登入用戶
export const mockCurrentUser = {
  id: "1",
  email: "admin@example.com",
  role: "admin",
}
