name: Docker Build and Push

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Debug step to check secrets availability (won't reveal actual values)
      - name: Debug - Check secrets availability
        run: |
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is set"
          else
            echo "DOCKERHUB_USERNAME is NOT set"
          fi
          
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is set"
          else
            echo "DOCKERHUB_TOKEN is NOT set"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Try direct Docker login instead of using the action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Generate tag based on git information
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short

      # Build and push production image
      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:prod
            ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push development image
      - name: Build and push development image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dev
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max 